name: Java CI with Gradle

on:
  workflow_dispatch:

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        include:
        - os: macos-latest
          arch: x64
          runner: macos-15-intel
          expander_leg: macos-latest--x64
    runs-on: ${{ matrix.runner }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        architecture: ${{ matrix.java-arch || matrix.arch }}
        cache: 'gradle'
    - name: Build dex-tools with Gradle
      shell: bash
      run: |
        ./gradlew "-DGITHUB_REF_NAME=${GITHUB_REF_NAME}" check distZip

    - name: Archive dex tools
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: dex-tools-${{ matrix.os }}-${{ matrix.arch }}
        path: dex-tools/build/distributions/dex-tools-*.zip
    name: build [${{ matrix.expander_leg }}]
    timeout-minutes: 150
